### PR TITLE
Removing BlueprintGraph that causes issues with packaged build.

### PR DESCRIPTION
**Pull request by sanxfxteam**
BTW amazingly simple library to use, a life saver.

### CODE REVIEW

**Comment by sanxfxteam** [comment]
It might be good to provide this code under an MIT license.

**Comment by LoborchukAndrii** [comment]
ok, I will add it

**Comment by LoborchukAndrii** [comment]
License added

**Comment by sanxfxteam** [comment]
Hi, thanks for adding the license, also the pull request here had a small change for Packaged builds, if you can merge please go ahead, if you can't I'll try again.

**Comment by LoborchukAndrii** [comment]
I'm writing an update right now, a small one, but I've incorporated your changes into it

**Comment by sanxfxteam** [comment]
Ok awesome.

**Comment by LoborchukAndrii** [comment]
Unfortunately my update will be a bit delayed, so I just threw in your changes, thanks for your feedback

**Pull request closed without merging**
